# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20))
y = x * 2 -1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 465ms/step - loss: 363.7979
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 363.3422
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 362.8868
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 362.4317
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 361.9769
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 361.5225
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 361.0683
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 360.6144
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 360.1609
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 359.7077


In [ ]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
model.predict(x).reshape(-1)

array([0.00999787, 0.22739449, 0.4447911 , 0.6621877 , 0.8795843 ,
       1.0969809 , 1.3143775 , 1.5317742 , 1.7491708 , 1.9665674 ,
       2.183964  , 2.4013605 , 2.6187572 , 2.836154  , 3.0535505 ,
       3.270947  , 3.4883437 , 3.7057405 , 3.923137  , 4.1405334 ],
      dtype=float32)

In [ ]:
y_pred = model.predict(x)

In [ ]:
for idx, val in enumerate(y_pred):
    if val >= .5 :
        y_pred[idx] = 1
    else :
        y_pred[idx] = 0

In [ ]:
y_pred

array([[0.00999787],
       [0.22739449],
       [0.4447911 ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ]], dtype=float32)

In [ ]:
bin_list = []

for i, v in enumerate(y_pred) :
    if y_pred[i] == 1 :
        bin_list.append(i)

In [ ]:
bin_list

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

## Now, Your turn!

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

In [ ]:
# 1번. 세션 클리어
keras.backend.clear_session()

# 2번. 모델 선언
model = keras.models.Sequential()

# 3번. 모델 블록 조립
## Original : Input Layer의 코드가 그 다음 레이어에 들어있다!
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

# 4번. 모델 컴파일
model.compile(loss='mse', optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

In [ ]:
model.predict(x)

## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam',
              metrics=['accuracy'])

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x[:15], y[:15], epochs=10, verbose=1)

# 결과 출력해줘!
print(y[15:])
print(model.predict(x[15:]))

## Now, Your turn!

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

In [ ]:
# 1번. 세션 클리어
keras.backend.clear_session()

# 2번. 모델 선언
model = keras.models.Sequential()

# 3번. 모델 블록 조립

## Original : Input Layer의 코드가 그 다음 레이어에 들어있다!
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1, activation='sigmoid') )

# 4번. 모델 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

In [ ]:
model.predict(x)