# 멀티클래스 분류 연습 (over 2진분류)

![iris_flower](https://www.embedded-robotics.com/wp-content/uploads/2022/01/Iris-Dataset-Classification-1024x367.png)

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

In [ ]:
x = iris.data
y = iris.target

In [ ]:
x.shape, y.shape

((150, 4), (150,))

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
# One-Hot Encoding
from tensorflow.keras.utils import to_categorical

In [ ]:
y = to_categorical(y, 3)

In [ ]:
x.shape, y.shape

((150, 4), (150, 3))

# 1번. Sequential API style로 모델링 하세요

    loss = 'categorical_crossentropy' 사용!

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(4,)) )
model.add( keras.layers.Dense(3, activation='softmax') )

# 오리지널 Sequential API
# model.add( keras.layers.Dense(3, input_shape=(4,), activation='softmax') )

# 4번 컴파일 
model.compile(loss='categorical_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 1s 7ms/step - loss: 2.1181 - accuracy: 0.6667
Epoch 2/10
5/5 [==============================] - 0s 11ms/step - loss: 2.0582 - accuracy: 0.6667
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 2.0010 - accuracy: 0.6667
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 1.9487 - accuracy: 0.6667
Epoch 5/10
5/5 [==============================] - 0s 5ms/step - loss: 1.8920 - accuracy: 0.6667
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 1.8422 - accuracy: 0.6667
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 1.7865 - accuracy: 0.6667
Epoch 8/10
5/5 [==============================] - 0s 5ms/step - loss: 1.7395 - accuracy: 0.6667
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 1.6837 - accuracy: 0.6667
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 1.6402 - accuracy: 0.6667


In [ ]:
y_pred = model.predict(x)

In [ ]:
y_pred

array([[0.7809959 , 0.0640289 , 0.15497519],
       [0.7330015 , 0.09962686, 0.16737166],
       [0.75272554, 0.07736265, 0.16991182],
       [0.71239644, 0.10612991, 0.18147366],
       [0.78302443, 0.05955631, 0.15741925],
       [0.79802203, 0.06251868, 0.13945922],
       [0.75620353, 0.07460935, 0.16918711],
       [0.7575328 , 0.07909014, 0.16337709],
       [0.6980029 , 0.11436113, 0.18763597],
       [0.72220165, 0.10190825, 0.17589013],
       [0.7963284 , 0.05826639, 0.14540519],
       [0.7348431 , 0.09064306, 0.17451377],
       [0.7224217 , 0.10020298, 0.17737526],
       [0.7367603 , 0.07606994, 0.18716973],
       [0.8526053 , 0.0296481 , 0.11774655],
       [0.85281223, 0.03053186, 0.11665587],
       [0.83540076, 0.03899242, 0.12560688],
       [0.78623265, 0.0643511 , 0.14941624],
       [0.7991569 , 0.06512272, 0.13572034],
       [0.79476446, 0.05590608, 0.14932945],
       [0.7505945 , 0.09423185, 0.15517364],
       [0.79363376, 0.06120526, 0.14516094],
       [0.

In [ ]:
import numpy as np

In [ ]:
y_pred[:3]

array([[0.7809959 , 0.0640289 , 0.15497519],
       [0.7330015 , 0.09962686, 0.16737166],
       [0.75272554, 0.07736265, 0.16991182]], dtype=float32)

In [ ]:
y_pred[:3].argmax(axis=1)

array([0, 0, 0])

In [ ]:
y.argmax(axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# 2번. Functional API style로 모델링 하세요

In [ ]:
x.shape, y.shape

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
# 1번. 세션 클리어
keras.backend.clear_session()

# 2번. 레이어 엮기
il = keras.layers.Input(shape=(4,))
ol = keras.layers.Dense(3, activation='softmax')(il)

# 3번. 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

# 4번. 모델 컴파일
model.compile(loss='categorical_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

In [ ]:
model.predict(x)