# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [4]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 12ms/step - loss: 156.4616
Epoch 2/10
1/1 [==============================] - 0s 1000us/step - loss: 156.1632
Epoch 3/10
1/1 [==============================] - 0s 1000us/step - loss: 155.8650
Epoch 4/10
1/1 [==============================] - 0s 0s/step - loss: 155.5671
Epoch 5/10
1/1 [==============================] - 0s 0s/step - loss: 155.2696
Epoch 6/10
1/1 [==============================] - 0s 1ms/step - loss: 154.9723
Epoch 7/10
1/1 [==============================] - 0s 0s/step - loss: 154.6754
Epoch 8/10
1/1 [==============================] - 0s 0s/step - loss: 154.3787
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 154.0824
Epoch 10/10
1/1 [==============================] - 0s 0s/step - loss: 153.7865


In [5]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
[9.9967839e-03 8.1847483e-01 1.6269529e+00 2.4354310e+00 3.2439091e+00
 4.0523872e+00 4.8608651e+00 5.6693435e+00 6.4778214e+00 7.2862992e+00
 8.0947771e+00 8.9032555e+00 9.7117329e+00 1.0520211e+01 1.1328690e+01
 1.2137167e+01 1.2945645e+01 1.3754124e+01 1.4562601e+01 1.5371079e+01]


## Now, Your turn!

In [6]:
x = np.array(range(0,20))
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [7]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [8]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 999us/step - loss: 853.2104
Epoch 2/10
1/1 [==============================] - 0s 1000us/step - loss: 852.5280
Epoch 3/10
1/1 [==============================] - 0s 0s/step - loss: 851.8457
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 851.1639
Epoch 5/10
1/1 [==============================] - 0s 999us/step - loss: 850.4822
Epoch 6/10
1/1 [==============================] - 0s 1000us/step - loss: 849.8009
Epoch 7/10
1/1 [==============================] - 0s 0s/step - loss: 849.1198
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 848.4391
Epoch 9/10
1/1 [==============================] - 0s 1000us/step - loss: 847.7588
Epoch 10/10
1/1 [==============================] - 0s 1000us/step - loss: 847.0788


In [9]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]
[-0.00999851  0.33585024  0.681699    1.0275476   1.3733964   1.7192452
  2.0650938   2.4109426   2.7567914   3.1026402   3.448489    3.7943375
  4.1401863   4.4860353   4.831884    5.177733    5.5235815   5.86943
  6.215279    6.5611277 ]


## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [ ]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

In [10]:
from sklearn.datasets import load_boston

In [11]:
boston = load_boston()

x = boston.data
y = boston.target

x.shape, y.shape

C:\Users\allsa\anaconda3\envs\kt-aivle\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California hous

((506, 13), (506,))

In [14]:
# Clear Keras backend
keras.backend.clear_session()

# make layers
il = keras.layers.Input(shape=(13,))
ol = keras.layers.Dense(1)(il)

# make model
model = keras.models.Model(inputs=il, outputs=ol)

# compile model
model.compile(optimizer='adam', loss='mse')

In [17]:
model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
16/16 [==============================] - 0s 937us/step - loss: 1900.8293
Epoch 2/100
16/16 [==============================] - 0s 625us/step - loss: 1814.3075
Epoch 3/100
16/16 [==============================] - 0s 750us/step - loss: 1736.1926
Epoch 4/100
16/16 [==============================] - 0s 688us/step - loss: 1666.8589
Epoch 5/100
16/16 [==============================] - 0s 750us/step - loss: 1596.2437
Epoch 6/100
16/16 [==============================] - 0s 812us/step - loss: 1528.4883
Epoch 7/100
16/16 [==============================] - 0s 625us/step - loss: 1466.4912
Epoch 8/100
16/16 [==============================] - 0s 750us/step - loss: 1401.9261
Epoch 9/100
16/16 [==============================] - 0s 687us/step - loss: 1341.1403
Epoch 10/100
16/16 [==============================] - 0s 750us/step - loss: 1281.4843
Epoch 11/100
16/16 [==============================] - 0s 687us/step - loss: 1223.3344
Epoch 12/100
16/16 [==============================] - 0s 688us/

In [18]:
print(y[:5])
print(model.predict(x[:5]).reshape(-1))

[24.  21.6 34.7 33.4 36.2]
[23.259842 25.7723   26.076101 22.812723 22.61089 ]


In [19]:
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

In [20]:
x = cancer.data
y = cancer.target

x.shape, y.shape

((569, 30), (569,))

In [42]:
# clear keras session
keras.backend.clear_session()

# make layers
il = keras.layers.Input(shape=(30, ))
ol = keras.layers.Dense(1, activation='hard_sigmoid')(il)

# make model
model = keras.models.Model(il, ol)

# compile model

model.compile(optimizer='adam', loss=keras.losses.binary_crossentropy, metrics=['accuracy'])

In [46]:
model.fit(x, y, epochs=200, verbose=1)

Epoch 1/200
18/18 [==============================] - 0s 944us/step - loss: 4.1133 - accuracy: 0.7258
Epoch 2/200
18/18 [==============================] - 0s 1ms/step - loss: 4.1091 - accuracy: 0.7241
Epoch 3/200
18/18 [==============================] - 0s 1ms/step - loss: 4.1073 - accuracy: 0.7258
Epoch 4/200
18/18 [==============================] - 0s 1ms/step - loss: 4.1068 - accuracy: 0.7258
Epoch 5/200
18/18 [==============================] - 0s 1ms/step - loss: 4.1064 - accuracy: 0.7258
Epoch 6/200
18/18 [==============================] - 0s 1ms/step - loss: 4.0859 - accuracy: 0.7258
Epoch 7/200
18/18 [==============================] - 0s 1ms/step - loss: 4.0571 - accuracy: 0.7293
Epoch 8/200
18/18 [==============================] - 0s 1000us/step - loss: 4.0321 - accuracy: 0.7293
Epoch 9/200
18/18 [==============================] - 0s 1ms/step - loss: 3.8182 - accuracy: 0.7329
Epoch 10/200
18/18 [==============================] - 0s 1ms/step - loss: 3.7002 - accuracy: 0.7452
Epoc

In [47]:
print(y[:25])
print(model.predict(x[:25]).reshape(-1))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0.]
