# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(0, 20))
y = x * 2 - 1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [4]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 11ms/step - loss: 1314.2976
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 1313.4307
Epoch 3/10
1/1 [==============================] - 0s 1000us/step - loss: 1312.5638
Epoch 4/10
1/1 [==============================] - 0s 0s/step - loss: 1311.6975
Epoch 5/10
1/1 [==============================] - 0s 0s/step - loss: 1310.8315
Epoch 6/10
1/1 [==============================] - 0s 1ms/step - loss: 1309.9658
Epoch 7/10
1/1 [==============================] - 0s 0s/step - loss: 1309.1003
Epoch 8/10
1/1 [==============================] - 0s 0s/step - loss: 1308.2351
Epoch 9/10
1/1 [==============================] - 0s 0s/step - loss: 1307.3704
Epoch 10/10
1/1 [==============================] - 0s 1000us/step - loss: 1306.5059


In [5]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [15]:
model.predict(x).reshape(1, -1)

array([[ 9.9989539e-03, -1.3188121e+00, -2.6476231e+00, -3.9764340e+00,
        -5.3052454e+00, -6.6340566e+00, -7.9628673e+00, -9.2916784e+00,
        -1.0620489e+01, -1.1949300e+01, -1.3278111e+01, -1.4606922e+01,
        -1.5935733e+01, -1.7264545e+01, -1.8593357e+01, -1.9922167e+01,
        -2.1250978e+01, -2.2579790e+01, -2.3908600e+01, -2.5237411e+01]],
      dtype=float32)

## Now, Your turn!

In [16]:
x = np.array(range(0, 20))
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [23]:
x.shape, y.shape

((20,), (20,))

In [17]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

# 4번 컴파일
model.compile(loss='mse', optimizer='adam')

In [18]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 1000us/step - loss: 455.1248
Epoch 2/10
1/1 [==============================] - 0s 0s/step - loss: 454.6351
Epoch 3/10
1/1 [==============================] - 0s 0s/step - loss: 454.1456
Epoch 4/10
1/1 [==============================] - 0s 1000us/step - loss: 453.6564
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 453.1675
Epoch 6/10
1/1 [==============================] - 0s 0s/step - loss: 452.6790
Epoch 7/10
1/1 [==============================] - 0s 0s/step - loss: 452.1907
Epoch 8/10
1/1 [==============================] - 0s 0s/step - loss: 451.7028
Epoch 9/10
1/1 [==============================] - 0s 1000us/step - loss: 451.2151
Epoch 10/10
1/1 [==============================] - 0s 1ms/step - loss: 450.7279


In [19]:
print(y)

[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [22]:
model.predict(x).reshape(1, -1)

array([[-0.00999779, -0.38871768, -0.7674376 , -1.1461575 , -1.5248774 ,
        -1.9035974 , -2.2823172 , -2.6610372 , -3.039757  , -3.4184768 ,
        -3.7971969 , -4.1759167 , -4.5546365 , -4.9333563 , -5.3120766 ,
        -5.6907964 , -6.069516  , -6.448236  , -6.826956  , -7.205676  ]],
      dtype=float32)

## Quick Logistic Regression!

In [24]:
import tensorflow as tf
import tensorflow.keras as keras

import numpy as np

In [25]:
x = np.array(range(0, 20))
y = np.array([0] * 10 + [1] * 10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [26]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add(keras.layers.Input(shape=(1,)))
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add(keras.layers.Dense(1, activation='sigmoid'))

# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [27]:
# 데이터를 넣어서 학습시키자!
model.fit(x[:15], y[:15], epochs=10, verbose=1)

# 결과 출력해줘!
print(y[15:])
print(model.predict(x[15:]))

Epoch 1/10
1/1 [==============================] - 0s 3ms/step - loss: 1.4596 - accuracy: 0.6667
Epoch 2/10
1/1 [==============================] - 0s 1000us/step - loss: 1.4559 - accuracy: 0.6000
Epoch 3/10
1/1 [==============================] - 0s 1000us/step - loss: 1.4522 - accuracy: 0.6000
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 1.4486 - accuracy: 0.6000
Epoch 5/10
1/1 [==============================] - 0s 0s/step - loss: 1.4449 - accuracy: 0.6000
Epoch 6/10
1/1 [==============================] - 0s 999us/step - loss: 1.4413 - accuracy: 0.6000
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 1.4377 - accuracy: 0.6000
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 1.4340 - accuracy: 0.6000
Epoch 9/10
1/1 [==============================] - 0s 999us/step - loss: 1.4304 - accuracy: 0.6000
Epoch 10/10
1/1 [==============================] - 0s 0s/step - loss: 1.4268 - accuracy: 0.6000
[1 1 1 1 1]
[[0.01014109]
 [0.0

## Now, Your turn!

In [33]:
x = np.array(range(0, 40))
y = np.array([0] * 20 + [1] * 20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [34]:
keras.backend.clear_session()

model = keras.Sequential()

model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')

In [37]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 3ms/step - loss: 4.8687 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 2ms/step - loss: 4.8591 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 1ms/step - loss: 4.8492 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 2ms/step - loss: 4.8400 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 3ms/step - loss: 4.8306 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 1ms/step - loss: 4.8212 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 1ms/step - loss: 4.8134 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 1ms/step - loss: 4.8035 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 1000us/step - loss: 4.7941 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 2ms/step - loss: 4.7845 - accuracy: 0.5250


In [38]:
print(y[30:])
print(model.predict(x[30:]).reshape(-1))

[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [83]:
from sklearn.datasets import load_boston

import pandas as pd
import numpy as np

In [84]:
boston = load_boston()

C:\Users\allsa\anaconda3\envs\kt-aivle\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California hous

In [85]:
x = boston.data
y = boston.target

In [86]:
x.shape, y.shape

((506, 13), (506,))

In [87]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=(13, )))
model.add(keras.layers.Dense(1))

model.compile(loss='mse', optimizer='adam')

In [88]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 625us/step - loss: 3642.8618
Epoch 2/10
16/16 [==============================] - 0s 652us/step - loss: 2238.9968
Epoch 3/10
16/16 [==============================] - 0s 563us/step - loss: 1340.3667
Epoch 4/10
16/16 [==============================] - 0s 687us/step - loss: 825.4426
Epoch 5/10
16/16 [==============================] - 0s 688us/step - loss: 577.9503
Epoch 6/10
16/16 [==============================] - 0s 500us/step - loss: 462.5356
Epoch 7/10
16/16 [==============================] - 0s 625us/step - loss: 409.4740
Epoch 8/10
16/16 [==============================] - 0s 625us/step - loss: 378.0310
Epoch 9/10
16/16 [==============================] - 0s 625us/step - loss: 354.2207
Epoch 10/10
16/16 [==============================] - 0s 688us/step - loss: 331.3064


In [89]:
print(y[:5])
print(model.predict(x[:5]))

[24.  21.6 34.7 33.4 36.2]
[[39.63984 ]
 [28.109968]
 [30.524786]
 [33.823395]
 [32.750984]]


In [90]:
from sklearn.datasets import load_breast_cancer

In [91]:
cancer = load_breast_cancer()

x = cancer.data
y = cancer.target

x.shape, y.shape

((569, 30), (569,))

In [104]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=(30, )))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics=['accuracy'])

In [108]:
model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
18/18 [==============================] - 0s 1ms/step - loss: 0.6652 - accuracy: 0.8822
Epoch 2/100
18/18 [==============================] - 0s 1ms/step - loss: 0.6647 - accuracy: 0.8787
Epoch 3/100
18/18 [==============================] - 0s 1ms/step - loss: 0.6673 - accuracy: 0.8840
Epoch 4/100
18/18 [==============================] - 0s 944us/step - loss: 0.6545 - accuracy: 0.8893
Epoch 5/100
18/18 [==============================] - 0s 833us/step - loss: 0.6432 - accuracy: 0.8858
Epoch 6/100
18/18 [==============================] - 0s 889us/step - loss: 0.6424 - accuracy: 0.8840
Epoch 7/100
18/18 [==============================] - 0s 833us/step - loss: 0.6308 - accuracy: 0.8858
Epoch 8/100
18/18 [==============================] - 0s 889us/step - loss: 0.6261 - accuracy: 0.8822
Epoch 9/100
18/18 [==============================] - 0s 889us/step - loss: 0.6298 - accuracy: 0.8875
Epoch 10/100
18/18 [==============================] - 0s 889us/step - loss: 0.6126 - accuracy: 0.

In [110]:
print(y[:25])
print(model.predict(x[:25]).reshape(-1))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0]
[9.2425439e-20 9.4688829e-18 1.0282814e-12 9.8846078e-01 4.8212492e-05
 4.0625197e-01 1.0895301e-12 1.2881524e-03 5.4899031e-01 2.7424721e-02
 1.5876814e-06 3.1175575e-09 1.1088346e-01 9.6249002e-01 9.9893385e-01
 1.8268402e-03 5.1758153e-08 1.1859712e-09 1.0661444e-30 9.9731809e-01
 9.9976748e-01 9.9999309e-01 4.8913702e-01 1.4771397e-35 1.0515861e-32]
