# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [1]:
from sklearn.datasets import load_breast_cancer

In [2]:
cancer = load_breast_cancer()

In [3]:
x = cancer.data
y = cancer.target

In [4]:
x.shape, y.shape

((569, 30), (569,))

In [55]:
#####################
# 라이브러리 불러오기
#####################
import keras
from keras.layers import Input, Dense
from keras.models import Model, Sequential
from sklearn.model_selection import train_test_split
from sklearn.metrics import *

import numpy as np

In [21]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=.3)

In [58]:
########
# 모델링
########
keras.backend.clear_session()

model = Sequential()

model.add(Input(shape=(30, )))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 31        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [59]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10)


Epoch 1/10
13/13 [==============================] - 0s 1ms/step - loss: 18.9279 - accuracy: 0.6382
Epoch 2/10
13/13 [==============================] - 0s 920us/step - loss: 6.3707 - accuracy: 0.6709
Epoch 3/10
13/13 [==============================] - 0s 997us/step - loss: 1.2954 - accuracy: 0.5879
Epoch 4/10
13/13 [==============================] - 0s 997us/step - loss: 1.0163 - accuracy: 0.6307
Epoch 5/10
13/13 [==============================] - 0s 997us/step - loss: 0.6991 - accuracy: 0.7990
Epoch 6/10
13/13 [==============================] - 0s 1ms/step - loss: 0.6196 - accuracy: 0.7839
Epoch 7/10
13/13 [==============================] - 0s 997us/step - loss: 0.5840 - accuracy: 0.7940
Epoch 8/10
13/13 [==============================] - 0s 1ms/step - loss: 0.5751 - accuracy: 0.8191
Epoch 9/10
13/13 [==============================] - 0s 1ms/step - loss: 0.5787 - accuracy: 0.7889
Epoch 10/10
13/13 [==============================] - 0s 1ms/step - loss: 0.5128 - accuracy: 0.8266


In [60]:
###########
# 모델 예측
###########
pred = model.predict(x_val)

print(classification_report(y_val, np.round(pred)))


              precision    recall  f1-score   support

           0       0.76      0.81      0.79        68
           1       0.87      0.83      0.85       103

    accuracy                           0.82       171
   macro avg       0.82      0.82      0.82       171
weighted avg       0.83      0.82      0.83       171



# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [61]:
########
# 모델링
########
keras.backend.clear_session()

il = Input(shape=(30, ))
h1 = Dense(32, activation='relu')(il)
h2 = Dense(32, activation='relu')(h1)
ol = Dense(1, activation='sigmoid')(h2)

model = Model(il, ol)

model.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics=['accuracy'])

model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 30)]              0         
_________________________________________________________________
dense (Dense)                (None, 32)                992       
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


In [62]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10)


Epoch 1/10
13/13 [==============================] - 0s 1ms/step - loss: 24.3765 - accuracy: 0.4497
Epoch 2/10
13/13 [==============================] - 0s 1ms/step - loss: 10.9969 - accuracy: 0.4045
Epoch 3/10
13/13 [==============================] - 0s 2ms/step - loss: 4.4861 - accuracy: 0.4372
Epoch 4/10
13/13 [==============================] - 0s 1ms/step - loss: 1.0059 - accuracy: 0.7136
Epoch 5/10
13/13 [==============================] - 0s 1ms/step - loss: 0.4398 - accuracy: 0.8819
Epoch 6/10
13/13 [==============================] - 0s 1ms/step - loss: 0.3536 - accuracy: 0.9045
Epoch 7/10
13/13 [==============================] - 0s 1ms/step - loss: 0.3169 - accuracy: 0.9020
Epoch 8/10
13/13 [==============================] - 0s 1ms/step - loss: 0.3078 - accuracy: 0.8970
Epoch 9/10
13/13 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8894
Epoch 10/10
13/13 [==============================] - 0s 1ms/step - loss: 0.3055 - accuracy: 0.9095


In [63]:
###########
# 모델 예측
###########
pred = model.predict(x_val)

print(classification_report(y_val, np.round(pred)))


              precision    recall  f1-score   support

           0       0.93      0.93      0.93        68
           1       0.95      0.95      0.95       103

    accuracy                           0.94       171
   macro avg       0.94      0.94      0.94       171
weighted avg       0.94      0.94      0.94       171



In [52]:
pred

array([[4.87466723e-01],
       [1.63953364e-01],
       [1.87428867e-07],
       [8.88817132e-01],
       [4.82405303e-03],
       [8.14722061e-01],
       [3.98412913e-01],
       [5.38616955e-01],
       [6.15519583e-01],
       [1.03113065e-02],
       [6.59144342e-01],
       [9.50102210e-01],
       [8.96802604e-01],
       [8.23129952e-01],
       [1.59600028e-03],
       [7.01034427e-01],
       [5.27398884e-01],
       [7.40216553e-01],
       [7.46138752e-01],
       [9.51649427e-01],
       [3.59666927e-07],
       [9.40363348e-01],
       [1.56169266e-01],
       [9.42253709e-01],
       [8.86111617e-01],
       [9.44623590e-01],
       [2.06864685e-01],
       [9.37068403e-01],
       [9.14432526e-01],
       [6.75161302e-01],
       [7.41811454e-01],
       [5.57716012e-01],
       [7.65369117e-01],
       [9.13964152e-01],
       [3.87241954e-08],
       [1.92720652e-01],
       [1.68930084e-01],
       [2.86049838e-03],
       [9.25654113e-01],
       [7.54233003e-01],


In [53]:
import numpy as np

In [65]:
np.round(pred).reshape((1, -1))

array([[1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
        1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1.,
        1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
        1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
        1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0.,
        1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
        1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
        1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
        0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.]], dtype=float32)

In [56]:
np.where(pred>.5, 1, 0)

array([[0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
    