# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [ ]:
### 라이브러리 불러오기

import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20))
y = x * 2 -1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
x.shape, y.shape

((20,), (20,))

In [ ]:
## 모델링 : Sequential API

# 1번. 세션 클리어 : 기존의 모델이 남아있다면 지워줘!
keras.backend.clear_session()

# 2번. 레이어 블록을 쌓을 발판 생성 : 레고처럼 차곡차곡!
model = keras.models.Sequential()

# 3번. 레이어 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

# 4번. 컴파일
model.compile(loss='mse', optimizer='adam')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [ ]:
## 모델 학습

model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 288ms/step - loss: 297.4402
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 297.0283
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 296.6166
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 296.2053
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 295.7943
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 295.3836
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 294.9731
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 294.5630
Epoch 9/10
1/1 [==============================] - 0s 21ms/step - loss: 294.1533
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 293.7438


In [ ]:
## 모델 예측

y_pred = model.predict(x)

y_pred[:5].reshape(-1)

array([0.00999764, 0.39186528, 0.77373296, 1.1556005 , 1.5374682 ],
      dtype=float32)

In [ ]:
# y_pred.shape

In [ ]:
y[:5]

array([-1,  1,  3,  5,  7])

## Now, Your turn!

In [ ]:
### 라이브러리 불러오기

import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [ ]:
## 모델 구조 확인을 위하여!

x.shape, y.shape

((20,), (20,))

In [ ]:
## 모델링 : Sequential API

## 1. 세션 클리어 : 메모리 청소
keras.backend.clear_session()

## 2. 레이어를 쌓을 발판 생성 : Sequential()
model = keras.models.Sequential()

## 3. 레이어 쌓기! : .add()
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 4. 컴파일
model.compile(loss='mse', optimizer='adam')

In [ ]:
## 모델 학습

model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 279ms/step - loss: 791.8920
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 791.2355
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 790.5793
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 789.9235
Epoch 5/10
1/1 [==============================] - 0s 13ms/step - loss: 789.2679
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 788.6125
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 787.9575
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 787.3030
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 786.6486
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 785.9946


In [ ]:
## 모델 학습

model.predict(x)[0].reshape(-1)

array([-0.00999837], dtype=float32)

In [ ]:
y[:5]

array([10,  7,  4,  1, -2])

## Quick Logistic Regression!

In [ ]:
## 라이브러리 불러오기

import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [ ]:
x.shape, y.shape

((20,), (20,))

In [ ]:
## 모델링 : Sequential API

# 1번 세션 클리어
keras.backend.clear_session()

# 2번 레이어 블록 발판 생성 : 차곡차곡 쌓을거야
model = keras.models.Sequential()

# 3번 .add()
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1, activation='sigmoid') )

# 4번 .compile()
model.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [ ]:
## 모델 학습

model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 332ms/step - loss: 0.4343 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 0.4342 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 15ms/step - loss: 0.4342 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 0.4341 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 0.4340 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 0.4340 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 0.4339 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 0.4338 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 0.4338 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 0.4337 - accuracy: 0.5500


In [ ]:
## 모델 예측값 생성

model.predict(x)[:5].reshape(-1)

array([0.5024999 , 0.20442232, 0.06135502, 0.01635644, 0.00421232],
      dtype=float32)

In [ ]:
y[:5]

array([0, 0, 0, 0, 0])

## Now, Your turn!

In [1]:
## 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [3]:
x.shape, y.shape

((40,), (40,))

In [17]:
## 모델링 : 이진분류 Sequential API

## 세션 클리어 : 청소!
keras.backend.clear_session()

## 모델 발판 생성 : 레이어를 차곡차곡 쌓을!
model = keras.models.Sequential()

## 레이어 조립 : .add()
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1, activation='sigmoid') )

## 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy', keras.metrics.BinaryAccuracy(threshold=1.0)],
              optimizer='adam')

In [18]:
## 학습

model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 7ms/step - loss: 1.8656 - accuracy: 0.5250 - binary_accuracy: 0.5000
Epoch 2/10
2/2 [==============================] - 0s 7ms/step - loss: 1.8557 - accuracy: 0.5250 - binary_accuracy: 0.5000
Epoch 3/10
2/2 [==============================] - 0s 7ms/step - loss: 1.8444 - accuracy: 0.5250 - binary_accuracy: 0.5000
Epoch 4/10
2/2 [==============================] - 0s 8ms/step - loss: 1.8363 - accuracy: 0.5250 - binary_accuracy: 0.5000
Epoch 5/10
2/2 [==============================] - 0s 8ms/step - loss: 1.8264 - accuracy: 0.5250 - binary_accuracy: 0.5000
Epoch 6/10
2/2 [==============================] - 0s 9ms/step - loss: 1.8172 - accuracy: 0.5250 - binary_accuracy: 0.5000
Epoch 7/10
2/2 [==============================] - 0s 8ms/step - loss: 1.8077 - accuracy: 0.5250 - binary_accuracy: 0.5000
Epoch 8/10
2/2 [==============================] - 0s 8ms/step - loss: 1.7987 - accuracy: 0.5250 - binary_accuracy: 0.5000
Epoch 9/10
2/2 [========

In [10]:
## 예측값 생성
model.predict(x).reshape(-1)

array([0.49520132, 0.754856  , 0.90623933, 0.9680909 , 0.9896084 ,
       0.99666584, 0.9989354 , 0.9996606 , 0.9998919 , 0.99996555,
       0.99998903, 0.9999965 , 0.9999989 , 0.99999964, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ],
      dtype=float32)

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])