# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

In [ ]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

In [ ]:
# 1번. 세션 클리어
keras.backend.clear_session()

# 2번. 레이어 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

# 3번. 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

# 4번. 모델 컴파일
model.compile(loss='mse', optimizer='adam')

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

In [ ]:
model.predict(x)

## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', metrics=['accuracy'],
              optimizer = 'adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [ ]:
# 1번. 세션 클리어
keras.backend.clear_session()

# 2번. 레이어 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

# 3번. 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

# 4번. 모델 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [ ]:
model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
2/2 [==============================] - 0s 7ms/step - loss: 5.7171 - accuracy: 0.5250
Epoch 2/100
2/2 [==============================] - 0s 6ms/step - loss: 5.7076 - accuracy: 0.5250
Epoch 3/100
2/2 [==============================] - 0s 5ms/step - loss: 5.6973 - accuracy: 0.5250
Epoch 4/100
2/2 [==============================] - 0s 7ms/step - loss: 5.6867 - accuracy: 0.5250
Epoch 5/100
2/2 [==============================] - 0s 5ms/step - loss: 5.6777 - accuracy: 0.5250
Epoch 6/100
2/2 [==============================] - 0s 5ms/step - loss: 5.6672 - accuracy: 0.5250
Epoch 7/100
2/2 [==============================] - 0s 8ms/step - loss: 5.6576 - accuracy: 0.5250
Epoch 8/100
2/2 [==============================] - 0s 6ms/step - loss: 5.6477 - accuracy: 0.5250
Epoch 9/100
2/2 [==============================] - 0s 8ms/step - loss: 5.6384 - accuracy: 0.5250
Epoch 10/100
2/2 [==============================] - 0s 7ms/step - loss: 5.6289 - accuracy: 0.5250
Epoch 11/100
2/2 [===========

In [ ]:
y_pred = model.predict(x)

In [ ]:
y_pred

array([[0.45177084],
       [0.6931891 ],
       [0.8610048 ],
       [0.9443939 ],
       [0.9789759 ],
       [0.99222803],
       [0.99715126],
       [0.99895906],
       [0.9996201 ],
       [0.99986136],
       [0.99994946],
       [0.9999815 ],
       [0.9999933 ],
       [0.99999756],
       [0.99999917],
       [0.99999964],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ]], dtype=float32)

In [ ]:
for idx, val in enumerate(y_pred) :
    if val >= 0.5 :
        y_pred[idx] = 1
    else :
        y_pred[idx] = 0

In [ ]:
y_pred

array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])