# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

x.shape, y.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


((20,), (20,))

In [7]:
## 모델링 : Functional API

# 1. 세션 클리어
keras.backend.clear_session()

# 2. 레이어끼리 사슬처럼 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

# 3. 인풋 레이어 / 아웃풋 레이어 지정
model = keras.models.Model(il, ol)

# 4. 컴파일
model.compile(loss='mse', optimizer='adam')

In [8]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 586ms/step - loss: 1235.8019
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 1234.9612
Epoch 3/10
1/1 [==============================] - 0s 14ms/step - loss: 1234.1207
Epoch 4/10
1/1 [==============================] - 0s 15ms/step - loss: 1233.2806
Epoch 5/10
1/1 [==============================] - 0s 18ms/step - loss: 1232.4410
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 1231.6016
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 1230.7623
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 1229.9236
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 1229.0852
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 1228.2468


In [9]:
# 모델 예측

model.predict(x)[:5].reshape(-1)

array([ 0.00999885, -1.2198849 , -2.4497685 , -3.6796522 , -4.909536  ],
      dtype=float32)

In [10]:
y[:5]

array([-1,  1,  3,  5,  7])

## Now, Your turn!

In [ ]:
## 라이브러리 불러오기
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [11]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

x.shape, y.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


((20,), (20,))

In [13]:
## Functional API

# 1 세션 클리어
keras.backend.clear_session()

# 2 레이어 사슬처럼 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

# 3 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

# 4 컴파일
model.compile(loss='mse', optimizer='adam')

In [14]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 340ms/step - loss: 279.3180
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 278.9433
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 278.5688
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 278.1946
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 277.8208
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 277.4473
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 277.0741
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 276.7011
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 276.3286
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 275.9564


In [15]:
# 예측
model.predict(x)[:5].reshape(-1)

array([-0.00999686, -0.821189  , -1.6323812 , -2.4435735 , -3.2547655 ],
      dtype=float32)

In [16]:
y[:5]

array([10,  7,  4,  1, -2])

## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [17]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [18]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [19]:
## shape : 구조 살펴보기
x.shape, y.shape

((40,), (40,))

In [21]:
## Functional API
# 1. 세션 클리어
keras.backend.clear_session()

# 2. 레이어 사슬처럼 엮기
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

# 3. 모델의 시작과 끝 레이어 지정
model = keras.models.Model(il, ol)

# 4. 컴파일
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [22]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 7ms/step - loss: 5.3887 - accuracy: 0.5000
Epoch 2/10
2/2 [==============================] - 0s 8ms/step - loss: 5.3605 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 8ms/step - loss: 5.3316 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 8ms/step - loss: 5.3013 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 7ms/step - loss: 5.2741 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 7ms/step - loss: 5.2438 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 5ms/step - loss: 5.2134 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 5ms/step - loss: 5.1844 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 5ms/step - loss: 5.1557 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 5ms/step - loss: 5.1280 - accuracy: 0.4750


In [23]:
# 예측
model.predict(x)

array([[5.04757941e-01],
       [4.20043081e-01],
       [3.39791119e-01],
       [2.67791986e-01],
       [2.06282169e-01],
       [1.55892670e-01],
       [1.16012901e-01],
       [8.53040218e-02],
       [6.21523261e-02],
       [4.49751616e-02],
       [3.23813558e-02],
       [2.32282281e-02],
       [1.66179836e-02],
       [1.18659735e-02],
       [8.46114755e-03],
       [6.02737069e-03],
       [4.29064035e-03],
       [3.05274129e-03],
       [2.17124820e-03],
       [1.54390931e-03],
       [1.09761953e-03],
       [7.80224800e-04],
       [5.54531813e-04],
       [3.94105911e-04],
       [2.80171633e-04],
       [1.99019909e-04],
       [1.41471624e-04],
       [1.00540849e-04],
       [7.14455091e-05],
       [5.07700206e-05],
       [3.60778067e-05],
       [2.56373150e-05],
       [1.82181775e-05],
       [1.29460514e-05],
       [9.19961712e-06],
       [6.53736242e-06],
       [4.64552659e-06],
       [3.30116586e-06],
       [2.34584741e-06],
       [1.66698669e-06]],