# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [ ]:
boston = load_boston()

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [12]:
# 1 세션 클리어
keras.backend.clear_session()

# 2 레이어 사슬처럼 엮기
il = keras.layers.Input(shape=(13,))
ol = keras.layers.Dense(1)(il)

# 3 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

# 4 컴파일
model.compile(loss='mse', optimizer='adam')

In [13]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 195346.9844
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 182607.4219
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 170349.4688
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 158755.3438
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 147835.4062
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 137332.9062
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 127457.0469
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 118254.0469
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 109455.3281
Epoch 10/10
16/16 [==============================] - 0s 3ms/step - loss: 101231.1172


In [15]:
# 예측
y_pred = model.predict(x)

y_pred[:5]

array([[288.1112 ],
       [270.59872],
       [266.1531 ],
       [254.16603],
       [256.02362]], dtype=float32)

In [16]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

# Logistic Regression 쬐금 더 어려운 데이터

In [17]:
from sklearn.datasets import load_breast_cancer

In [18]:
cancer = load_breast_cancer()

In [19]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것

In [20]:
x.shape, y.shape

((569, 30), (569,))

In [36]:
# 1. 청소!
keras.backend.clear_session()

# 2. 레이어 엮기!
il = keras.layers.Input(shape=(30,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

# 3. 시작 끝 지정!
model = keras.models.Model(il, ol)

# 4. 컴파일
model.compile(loss=keras.losses.binary_crossentropy, metrics=['accuracy'], optimizer='adam')

In [37]:
# 학습
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
18/18 [==============================] - 0s 2ms/step - loss: 70.4040 - accuracy: 0.6274
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 52.6697 - accuracy: 0.6274
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 35.7691 - accuracy: 0.4640
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 28.2315 - accuracy: 0.1793
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 26.8354 - accuracy: 0.1301
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 26.0526 - accuracy: 0.1371
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 25.2881 - accuracy: 0.1441
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 24.4883 - accuracy: 0.1441
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 23.7409 - accuracy: 0.1511
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 22.8680 - accuracy: 0.1599


In [38]:
# 예측
y_pred = model.predict(x)

y_pred[:10]

array([[1.000000e+00],
       [1.000000e+00],
       [1.000000e+00],
       [1.000000e+00],
       [8.217565e-22],
       [1.000000e+00],
       [1.000000e+00],
       [1.000000e+00],
       [9.999990e-01],
       [1.000000e+00]], dtype=float32)

In [39]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])