# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [5]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [6]:
from sklearn.datasets import load_boston

In [7]:
boston = load_boston()

In [8]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [10]:
## 1번 세션 클리어
keras.backend.clear_session()

## 2번 모델 선언 : Sequential()
model = keras.models.Sequential()

## 3번 레이어 조립
model.add( keras.layers.Input(shape=(13,)) )
model.add( keras.layers.Dense(1) )

## 4번 컴파일
model.compile(loss='mse', optimizer='adam')

In [11]:
## 모델 학습

model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 5012.0767
Epoch 2/10
16/16 [==============================] - 0s 978us/step - loss: 3767.1831
Epoch 3/10
16/16 [==============================] - 0s 999us/step - loss: 2968.0452
Epoch 4/10
16/16 [==============================] - 0s 986us/step - loss: 2537.4111
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 2274.9951
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 2116.7146
Epoch 7/10
16/16 [==============================] - 0s 902us/step - loss: 1987.2972
Epoch 8/10
16/16 [==============================] - 0s 915us/step - loss: 1872.5282
Epoch 9/10
16/16 [==============================] - 0s 995us/step - loss: 1758.6877
Epoch 10/10
16/16 [==============================] - 0s 902us/step - loss: 1651.1053


In [12]:
## 모델 예측

model.predict(x)[:5].reshape(-1)

array([ -3.5639904, -28.290894 , -18.424656 ,  -9.047094 , -13.758569 ],
      dtype=float32)

In [13]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

# Logistic Regression 쬐금 더 어려운 데이터

In [14]:
from sklearn.datasets import load_breast_cancer

In [15]:
cancer = load_breast_cancer()

In [16]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [19]:
## 모델링 : 이진 분류 Sequential

## 1번 세션 클리어
keras.backend.clear_session()

## 2번 모델 선언
model = keras.models.Sequential()

## 3번 레이어 조립
model.add( keras.layers.Input(shape=(30,)))
model.add( keras.layers.Dense(1, activation='sigmoid') )

## 4번 컴파일
model.compile(loss=keras.losses.binary_crossentropy, metrics=['accuracy'],
              optimizer='adam')

In [23]:
## 학습
model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
18/18 [==============================] - 0s 1ms/step - loss: 5.4389 - accuracy: 0.6626
Epoch 2/100
18/18 [==============================] - 0s 1ms/step - loss: 5.3500 - accuracy: 0.6608
Epoch 3/100
18/18 [==============================] - 0s 999us/step - loss: 5.2508 - accuracy: 0.6661
Epoch 4/100
18/18 [==============================] - 0s 1ms/step - loss: 5.1575 - accuracy: 0.6643
Epoch 5/100
18/18 [==============================] - 0s 1ms/step - loss: 5.0645 - accuracy: 0.6714
Epoch 6/100
18/18 [==============================] - 0s 1ms/step - loss: 4.9728 - accuracy: 0.6696
Epoch 7/100
18/18 [==============================] - 0s 1ms/step - loss: 4.8801 - accuracy: 0.6784
Epoch 8/100
18/18 [==============================] - 0s 1ms/step - loss: 4.7947 - accuracy: 0.6801
Epoch 9/100
18/18 [==============================] - 0s 1ms/step - loss: 4.7000 - accuracy: 0.6889
Epoch 10/100
18/18 [==============================] - 0s 1ms/step - loss: 4.6180 - accuracy: 0.6819
Epoch 1

In [24]:
## 예측값 생성
model.predict(x)[:30].reshape(-1)

array([1.3821471e-24, 1.8140353e-31, 2.2839040e-29, 1.0000000e+00,
       3.2846648e-33, 9.9999851e-01, 2.9658111e-15, 1.3092545e-01,
       9.9999619e-01, 9.9999762e-01, 4.9709229e-07, 1.0711166e-06,
       1.8380290e-27, 1.8069922e-07, 9.9998021e-01, 9.2846173e-01,
       1.9239485e-03, 1.1649457e-06, 4.5818278e-31, 9.9305505e-01,
       9.9999493e-01, 1.0000000e+00, 5.9907436e-03, 2.1484804e-34,
       3.4654934e-15, 1.9476518e-18, 9.9990559e-01, 5.7185945e-26,
       7.4592453e-01, 3.1176430e-15], dtype=float32)

In [25]:
y[:30]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0])