In [13]:
import pickle

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('/Users/cyeongy/PycharmProjects/pythonProject/web_crawling/data/premierleague.csv')

In [3]:
df.head()

name   gf  ga  points
0    Manchester City  106  27     100
1  Manchester United   68  28      81
2  Tottenham Hotspur   74  36      77
3          Liverpool   84  38      75
4            Chelsea   62  38      70

In [4]:
feature = df[['gf', 'ga']]

In [5]:
target = df['points']

In [6]:
model = LinearRegression().fit(feature, target)

In [7]:
np.round(model.predict([[80, 36]]))

/Users/cyeongy/opt/anaconda3/envs/kt-aivle/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([79.])

In [8]:
import warnings

warnings.filterwarnings('ignore')

In [10]:
np.round(model.predict([[80, 36]]))

array([79.])

In [24]:
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [25]:
with open('model.pkl', 'rb') as f:
    load_model = pickle.load(f)

In [28]:
load_model.predict([[80, 36]])

array([78.90247916])